int chandir(char **aa);
int echof(char **aa);
int execu(char **aa,char *acc);
char *line_read();
int lsf(char **aa);
int pinf(char **aa);
int pwdf(char **aa);
char *replace_str(char *str, char *orig, char *rep);
char **line_split(char *inp,char *del);
int sys_execu(char **aa,char *acc);
void handch(int a);
char **redif(char **aa);
void pipef(char **aa);
int jobf(char **aa);
int setenvf(char **aa);
int usetenvf(char **aa);
int kjobf(char **aa);
int okillf(char **aa);
int fgf(char **aa);
int bgf(char **aa);
void hch(int a);